name: Publish package to GitHub Packages
on:
  release:
    types: [published]
jobs:
  publish-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup protoc
        run: scripts/install_protoc.sh
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish to GitHub Packages
        run: ./java/gradlew -p java version
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}